/**
 * Lingua del pannello: italiano per il cliente, romeno per chi lo ha
 * costruito. La scelta resta nel localStorage e vale per tutte le pagine.
 *
 * Nessun framework: il pannello è scritto nello stesso stile del resto del
 * sito, che non carica React né Preact. Su un telefono vecchio la differenza
 * fra qualche kilobyte di codice nostro e mezzo megabyte di libreria si
 * sente tutta, e questo pannello lo userà un artigiano, spesso dal cantiere.
 *
 * Gli accenti non sono facoltativi: "e" al posto di "è" si legge come testo
 * scritto da una macchina. Chi aggiunge una chiave li mette.
 */

const CHIAVE = 'mda-admin-lingua'

export type Lingua = 'it' | 'ro'

const TESTI = {
  it: {
    'menu.aria': 'Sezioni del pannello',
    'menu.pannello': 'Pannello',
    'menu.richieste': 'Richieste',
    'menu.blog': 'Blog',
    'menu.lavori': 'Lavori',
    'menu.recensioni': 'Recensioni',
    'menu.statistiche': 'Statistiche',
    'menu.link': 'Link',
    'menu.impostazioni': 'Impostazioni',
    'menu.vediSito': 'Vedi il sito',
    'menu.esci': 'Esci',
    'menu.contenuti': 'Contenuti',
    'menu.clienti': 'Clienti',
    'menu.analisi': 'Analisi',
    'menu.altro': 'Altro',
    'menu.nuoveRichieste': 'richieste da leggere',

    'locale.titolo': 'Modalità di prova: i dati restano in questo browser',
    'locale.testo':
      'Il pannello non è collegato al database: quello che scrivi rimane su questo computer e non arriva al sito. Per collegarlo servono le due variabili PUBLIC_SUPABASE_URL e PUBLIC_SUPABASE_ANON_KEY.',

    'accesso.titolo': 'Area riservata',
    'accesso.sottotitolo': 'Entra per gestire il sito.',
    'accesso.frase': 'Il tuo sito, sempre aggiornato: richieste, lavori, recensioni e articoli in un posto solo.',
    'accesso.email': 'Email',
    'accesso.password': 'Password',
    'accesso.entra': 'Entra',
    'accesso.attesa': 'Un momento',
    'accesso.errore': 'Email o password non corretti.',
    'accesso.nonAutorizzato': 'Questo account non ha accesso al pannello.',
    'accesso.locale': 'In modalità di prova si entra senza password.',
    'accesso.entraProva': 'Entra in modalità di prova',
    'accesso.mostraPassword': 'Mostra la password',
    'accesso.nascondiPassword': 'Nascondi la password',
    'accesso.dimenticata': 'Password dimenticata?',
    'accesso.recuperoTitolo': 'Recupera la password',
    'accesso.recuperoTesto': 'Scrivi la tua email: ti arriva un collegamento per scegliere una password nuova.',
    'accesso.recuperoInvia': 'Mandami il collegamento',
    'accesso.recuperoInviato': 'Fatto. Controlla la posta, anche nello spam, e apri il collegamento.',
    'accesso.torna': 'Torna all’accesso',
    'accesso.nuovaPasswordTitolo': 'Scegli una password nuova',
    'accesso.nuovaPasswordTesto': 'Almeno 8 caratteri. Scrivila due volte per sicurezza.',
    'accesso.nuovaPassword': 'Nuova password',
    'accesso.confermaPassword': 'Ripeti la password',
    'accesso.salvaPassword': 'Salva la password',
    'accesso.passwordCambiata': 'Password cambiata. Da adesso entri con quella nuova.',
    'accesso.passwordCorta': 'La password deve avere almeno 8 caratteri.',
    'accesso.passwordDiverse': 'Le due password non coincidono.',

    'pannello.titolo': 'Pannello',
    'pannello.buongiorno': 'Buongiorno',
    'pannello.buonPomeriggio': 'Buon pomeriggio',
    'pannello.buonasera': 'Buonasera',
    'pannello.benvenuto': 'Ecco come sta il sito adesso.',
    'pannello.nuovoArticolo': 'Nuovo articolo',
    'pannello.oggi': 'Oggi',
    'pannello.setteGiorni': 'Ultimi 7 giorni',
    'pannello.trentaGiorni': 'Ultimi 30 giorni',
    'pannello.visualizzazioni': 'visualizzazioni',
    'pannello.visiteUniche': 'visite uniche',
    'pannello.vediStatistiche': 'Vedi tutte le statistiche',
    'pannello.richiesteNuove': 'Richieste da leggere',
    'pannello.richiesteNuoveNota': 'persone che aspettano una risposta',
    'pannello.nessunaNuova': 'Tutto risposto, bravo.',
    'pannello.vediRichieste': 'Vedi le richieste',
    'pannello.ultimeRichieste': 'Ultime richieste',
    'pannello.nessunaRichiesta': 'Nessuna richiesta ancora. Arriveranno qui appena qualcuno compila un modulo sul sito.',
    'pannello.ultimiArticoli': 'Ultimi articoli',
    'pannello.nessunArticolo': 'Ancora nessun articolo. Premi "Nuovo articolo" e scrivi il primo.',
    'pannello.scorciatoie': 'Scorciatoie',
    'pannello.scriviArticoli': 'Scrivi un articolo',
    'pannello.aggiungiLavoro': 'Aggiungi un cantiere',
    'pannello.aggiungiRecensione': 'Aggiungi una recensione',
    'pannello.creaLink': 'Crea un link di tracciamento',
    'pannello.vediTraffico': 'Vedi i numeri del traffico',
    'pannello.cambiaDati': 'Cambia telefono e dati',
    'pannello.ilSito': 'Il sito',
    'pannello.articoliPubblicati': 'articoli pubblicati',
    'pannello.recensioniAttive': 'recensioni sul sito',
    'pannello.cantieri': 'cantieri in galleria',
    'pannello.esempiAttivi': 'Il sito mostra ancora gli esempi: aggiungi i tuoi lavori e le recensioni vere.',
    'pannello.curva': 'Andamento del mese',

    'richieste.titolo': 'Richieste',
    'richieste.sottotitolo': 'Chi ha compilato un modulo sul sito. Chiama, scrivi su WhatsApp, segna quando hai risposto.',
    'richieste.tutte': 'Tutte',
    'richieste.nuove': 'Da leggere',
    'richieste.contattate': 'Contattate',
    'richieste.chiuse': 'Chiuse',
    'richieste.vuoto': 'Nessuna richiesta ancora.',
    'richieste.vuotoNuove': 'Nessuna richiesta da leggere. Ottimo.',
    'richieste.vuotoFiltro': 'Niente in questa lista.',
    'richieste.tipoRichiamo': 'Richiamo',
    'richieste.tipoPreventivo': 'Preventivo',
    'richieste.chiama': 'Chiama',
    'richieste.whatsapp': 'WhatsApp',
    'richieste.email': 'Email',
    'richieste.statoNuova': 'Da leggere',
    'richieste.statoContattata': 'Contattata',
    'richieste.statoChiusa': 'Chiusa',
    'richieste.segnaContattata': 'Segna come contattata',
    'richieste.segnaChiusa': 'Chiudi',
    'richieste.riapri': 'Riapri',
    'richieste.nota': 'Appunti',
    'richieste.notaSegnaposto': 'Es. richiamare martedì, vuole il sopralluogo di sabato',
    'richieste.salvaNota': 'Salva gli appunti',
    'richieste.cancella': 'Cancella',
    'richieste.confermaCancella': 'Cancellare questa richiesta? Non si torna indietro.',
    'richieste.dettagli': 'Dettagli',
    'richieste.comune': 'Comune',
    'richieste.servizio': 'Servizio',
    'richieste.messaggio': 'Messaggio',
    'richieste.stima': 'Stima mostrata',
    'richieste.pagina': 'Pagina',
    'richieste.arrivataDa': 'Arrivata dal link',
    'richieste.ricevuta': 'Ricevuta',
    'richieste.senzaNome': 'Senza nome',
    'richieste.cerca': 'Cerca per nome, telefono o comune',
    'richieste.whatsappTesto': 'Buongiorno, sono MDA Impresa Edile. Ho ricevuto la sua richiesta dal sito.',

    'blog.titolo': 'Blog',
    'blog.sottotitolo': 'Gli articoli pubblicati sul sito. Ogni articolo aiuta il sito su Google.',
    'blog.nuovo': 'Nuovo articolo',
    'blog.vuoto': 'Ancora nessun articolo.',
    'blog.vuotoTesto': 'Un articolo al mese su tetti, infiltrazioni e manutenzione porta visite da Google per anni.',
    'blog.bozza': 'Bozza',
    'blog.pubblicato': 'Pubblicato',
    'blog.modifica': 'Modifica',
    'blog.cancella': 'Cancella',
    'blog.confermaCancella': 'Cancellare questo articolo? Non si torna indietro.',
    'blog.tuttiArticoli': 'Tutti gli articoli',
    'blog.nuovoTitolo': 'Nuovo articolo',
    'blog.modificaTitolo': 'Modifica articolo',
    'blog.campoTitolo': 'Titolo',
    'blog.segnapostoTitolo': 'Es. Quando conviene rifare il tetto invece di ripararlo',
    'blog.campoSlug': 'Indirizzo (slug)',
    'blog.aiutoSlug': 'L’articolo avrà l’indirizzo',
    'blog.slugOccupato': 'Un altro articolo usa già questo indirizzo.',
    'blog.campoEstratto': 'Introduzione',
    'blog.aiutoEstratto': 'Una o due frasi mostrate nella lista del blog e su Google.',
    'blog.campoCopertina': 'Immagine di copertina',
    'blog.scegliImmagine': 'Carica una foto',
    'blog.togliCopertina': 'Togli la copertina',
    'blog.campoContenuto': 'Contenuto',
    'blog.segnapostoContenuto':
      'Scrivi qui l’articolo.\n\nLe righe vuote creano nuovi paragrafi. Usa i pulsanti sopra per grassetto, corsivo, sottotitoli, elenchi, link e foto.',
    'blog.anteprima': 'Così apparirà sul sito',
    'blog.anteprimaVuota': 'L’anteprima appare mentre scrivi.',
    'blog.salva': 'Salva',
    'blog.salvato': 'Salvato',
    'blog.grassetto': 'Grassetto',
    'blog.corsivo': 'Corsivo',
    'blog.sottotitolo2': 'Sottotitolo',
    'blog.elenco': 'Elenco',
    'blog.link': 'Link',
    'blog.immagine': 'Foto',
    'blog.chiediLink': 'Indirizzo del link',
    'blog.serveTitolo': 'Serve almeno un titolo per salvare.',
    'blog.vediSulSito': 'Vedi sul sito',
    'blog.parole': 'parole',
    'blog.minutiLettura': 'min di lettura',
    'blog.pubblicaNota': 'Spento: l’articolo resta una bozza che vedi solo tu. Acceso: va sul sito.',
    'blog.stato': 'Stato',

    'lavori.titolo': 'Lavori',
    'lavori.sottotitolo':
      'I cantieri con la foto prima e dopo, come appaiono sul sito. Finché non ne aggiungi uno, il sito mostra gli esempi.',
    'lavori.nuovo': 'Nuovo cantiere',
    'lavori.vuotoTitolo': 'Ancora nessun cantiere tuo',
    'lavori.vuotoTesto':
      'Il sito mostra cinque esempi. Aggiungi il primo lavoro vero con due foto, prima e dopo, e gli esempi spariscono.',
    'lavori.esempiNota': 'Sul sito ci sono ancora gli esempi: appena un tuo cantiere è visibile, prendono il loro posto.',
    'lavori.nuovoTitolo': 'Nuovo cantiere',
    'lavori.modificaTitolo': 'Modifica cantiere',
    'lavori.campoTitolo': 'Titolo',
    'lavori.segnapostoTitolo': 'Es. Rifacimento tetto a Portogruaro',
    'lavori.campoLocalita': 'Comune',
    'lavori.segnapostoLocalita': 'Es. Portogruaro (VE)',
    'lavori.campoTesto': 'Descrizione',
    'lavori.segnapostoTesto': 'Es. Rifacimento completo della copertura in tegole portoghesi con isolamento in lana di roccia.',
    'lavori.campoDurata': 'Tempo di posa',
    'lavori.segnapostoDurata': 'Es. 8 giorni lavorativi',
    'lavori.campoMateriali': 'Materiali usati',
    'lavori.segnapostoMateriali': 'Es. Lana minerale, rame, tegole',
    'lavori.prima': 'Prima',
    'lavori.dopo': 'Dopo',
    'lavori.caricaFoto': 'Carica la foto',
    'lavori.cambiaFoto': 'Cambia',
    'lavori.visibile': 'Visibile sul sito',
    'lavori.nascosto': 'Nascosto',
    'lavori.salva': 'Salva',
    'lavori.cancella': 'Cancella',
    'lavori.confermaCancella': 'Cancellare questo cantiere? Le foto spariscono dal sito.',
    'lavori.serveTitolo': 'Serve un titolo.',
    'lavori.serveFoto': 'Servono tutte e due le foto, prima e dopo.',
    'lavori.su': 'Sposta su',
    'lavori.giu': 'Sposta giù',
    'lavori.modifica': 'Modifica',

    'recensioni.titolo': 'Recensioni',
    'recensioni.sottotitolo':
      'Le parole dei tuoi clienti, copiate da Google o dai messaggi che ti mandano. Finché non ne aggiungi una, il sito mostra gli esempi.',
    'recensioni.nuova': 'Nuova recensione',
    'recensioni.vuotoTitolo': 'Ancora nessuna recensione tua',
    'recensioni.vuotoTesto': 'Copia qui le recensioni vere dei tuoi clienti: nome, comune e le loro parole. Gli esempi spariscono da soli.',
    'recensioni.esempiNota': 'Sul sito ci sono ancora gli esempi: appena una tua recensione è visibile, prendono il loro posto.',
    'recensioni.googleNota': 'Solo recensioni vere: quelle inventate sono pubblicità ingannevole e Google le punisce.',
    'recensioni.nuovaTitolo': 'Nuova recensione',
    'recensioni.modificaTitolo': 'Modifica recensione',
    'recensioni.campoNome': 'Nome del cliente',
    'recensioni.segnapostoNome': 'Es. Giovanni S.',
    'recensioni.campoLocalita': 'Comune',
    'recensioni.segnapostoLocalita': 'Es. San Donà di Piave (VE)',
    'recensioni.campoTesto': 'Recensione',
    'recensioni.segnapostoTesto': 'Le parole del cliente, così come le ha scritte.',
    'recensioni.campoVoto': 'Stelle',
    'recensioni.stelle': 'stelle su 5',
    'recensioni.campoFoto': 'Foto (facoltativa)',
    'recensioni.caricaFoto': 'Carica una foto',
    'recensioni.togliFoto': 'Togli la foto',
    'recensioni.fotoNota': 'Senza foto il sito mostra le iniziali del nome.',
    'recensioni.visibile': 'Visibile sul sito',
    'recensioni.nascosta': 'Nascosta',
    'recensioni.salva': 'Salva',
    'recensioni.cancella': 'Cancella',
    'recensioni.confermaCancella': 'Cancellare questa recensione?',
    'recensioni.serveTesto': 'Servono il nome e il testo della recensione.',
    'recensioni.su': 'Sposta su',
    'recensioni.giu': 'Sposta giù',
    'recensioni.modifica': 'Modifica',

    'statistiche.titolo': 'Statistiche',
    'statistiche.sottotitolo': 'Le visite del sito, senza cookie e senza salvare nulla sui visitatori.',
    'statistiche.settegiorni': '7 giorni',
    'statistiche.trentagiorni': '30 giorni',
    'statistiche.novantagiorni': '90 giorni',
    'statistiche.dodicimesi': '12 mesi',
    'statistiche.visualizzazioni': 'Visualizzazioni di pagina',
    'statistiche.uniche': 'Visite uniche',
    'statistiche.piuVista': 'Pagina più vista',
    'statistiche.daMobile': 'Da telefono',
    'statistiche.periodo': 'nel periodo scelto',
    'statistiche.sessioni': 'sessioni, una per visitatore e scheda',
    'statistiche.percentuale': 'percentuale sulle sessioni',
    'statistiche.visitePerGiorno': 'Visite per giorno',
    'statistiche.vediTabella': 'Vedi la tabella',
    'statistiche.vediGrafico': 'Vedi il grafico',
    'statistiche.paginePiuViste': 'Pagine più viste',
    'statistiche.provenienza': 'Da dove sono arrivate le visite',
    'statistiche.dispositivi': 'Dispositivi',
    'statistiche.trafficoLink': 'Traffico dai tuoi link',
    'statistiche.diretto': 'Diretto o indirizzo digitato',
    'statistiche.computer': 'Computer',
    'statistiche.telefono': 'Telefono',
    'statistiche.nessunDato': 'Ancora nessun dato per questo periodo.',
    'statistiche.giorno': 'Giorno',
    'statistiche.nota': 'Le tue visite dal pannello non vengono contate.',

    'link.titolo': 'Link',
    'link.sottotitolo':
      'Indirizzi da usare in un annuncio, su un volantino o su Facebook: chi entra da qui viene contato a parte, così sai cosa funziona.',
    'link.nuovo': 'Nuovo link',
    'link.etichetta': 'Nome (per te)',
    'link.segnapostoEtichetta': 'Es. Volantino settembre',
    'link.codice': 'Codice',
    'link.destinazione': 'Dove porta',
    'link.crea': 'Crea',
    'link.copia': 'Copia',
    'link.copiato': 'Copiato',
    'link.cancella': 'Cancella',
    'link.confermaCancella': 'Cancellare questo link? Chi lo apre finirà comunque sulla home.',
    'link.vuoto': 'Ancora nessun link.',
    'link.vuotoTesto': 'Crea un link diverso per ogni volantino o annuncio e scopri quale porta più visite.',
    'link.visite': 'Visite',
    'link.visualizzazioni': 'Visualizzazioni',
    'link.serveEtichetta': 'Serve un nome e un codice.',
    'link.codiceUsato': 'Questo codice esiste già.',
    'link.home': 'Home',
    'link.servizi': 'Servizi',
    'link.guide': 'Guide',
    'link.zone': 'Zone servite',
    'link.preventivo': 'Preventivo (home)',
    'link.blog': 'Blog',

    'impostazioni.titolo': 'Impostazioni',
    'impostazioni.sottotitolo': 'I dati dell’impresa che compaiono sul sito. Quello che lasci vuoto resta com’è adesso.',
    'impostazioni.contatti': 'Contatti',
    'impostazioni.contattiNota': 'Compaiono in cima, nel piè di pagina e nei pulsanti di chiamata.',
    'impostazioni.telefono': 'Telefono',
    'impostazioni.aiutoTelefono': 'Come lo vuoi vedere scritto, es. +39 389 999 7498',
    'impostazioni.whatsapp': 'Numero WhatsApp',
    'impostazioni.aiutoWhatsapp': 'Solo cifre con il prefisso, es. 393899997498. Vuoto: usa il telefono.',
    'impostazioni.email': 'Email',
    'impostazioni.orari': 'Orari',
    'impostazioni.aiutoOrari': 'Es. Lun - Sab, 08:00 - 18:00',
    'impostazioni.oreRisposta': 'Rispondi entro (ore)',
    'impostazioni.garanziaAnni': 'Garanzia (anni)',
    'impostazioni.sede': 'Sede',
    'impostazioni.via': 'Via e numero',
    'impostazioni.cap': 'CAP',
    'impostazioni.citta': 'Comune',
    'impostazioni.provincia': 'Sigla provincia',
    'impostazioni.aiutoProvincia': 'Es. VE',
    'impostazioni.provinciaNome': 'Nome provincia',
    'impostazioni.aiutoProvinciaNome': 'Es. Venezia',
    'impostazioni.legale': 'Dati legali',
    'impostazioni.legaleNota':
      'Obbligatori per legge su un sito aziendale in Italia. Finché mancano, il sito non li pubblica e non inventa nulla.',
    'impostazioni.ragioneSociale': 'Ragione sociale',
    'impostazioni.aiutoRagioneSociale': 'Es. MDA Impresa Edile S.r.l., come sulla visura',
    'impostazioni.partitaIva': 'Partita IVA',
    'impostazioni.aiutoPartitaIva': 'Undici cifre, es. IT01234567890',
    'impostazioni.rea': 'Numero REA',
    'impostazioni.aiutoRea': 'Es. VE-123456. Vuoto se l’impresa non è iscritta.',
    'impostazioni.social': 'Social',
    'impostazioni.instagram': 'Pagina Instagram',
    'impostazioni.facebook': 'Pagina Facebook',
    'impostazioni.salva': 'Salva le impostazioni',
    'impostazioni.salvato': 'Impostazioni salvate',
    'impostazioni.pubblicazione': 'Pubblicazione',
    'impostazioni.pubblicazioneNota':
      'Il sito si rigenera da solo quando premi Pubblica. Le richieste e le statistiche non ne hanno bisogno.',
    'impostazioni.hook': 'Indirizzo di pubblicazione (Deploy Hook di Vercel)',
    'impostazioni.aiutoHook': 'Lo crea chi ha costruito il sito, da Vercel: Settings, Git, Deploy Hooks. Va incollato qui una volta sola.',
    'impostazioni.salvaHook': 'Salva l’indirizzo',
    'impostazioni.account': 'Il tuo accesso',
    'impostazioni.accountEmail': 'Entri con',
    'impostazioni.nuovaPassword': 'Nuova password',
    'impostazioni.confermaPassword': 'Ripeti la nuova password',
    'impostazioni.cambiaPassword': 'Cambia la password',
    'impostazioni.passwordCambiata': 'Password cambiata',
    'impostazioni.lingua': 'Lingua del pannello',

    'pubblica.daPubblicare': 'Ci sono modifiche non ancora sul sito.',
    'pubblica.pubblica': 'Pubblica sul sito',
    'pubblica.inCorso': 'Pubblicazione in corso, ci vogliono circa due minuti.',
    'pubblica.fatto': 'Pubblicazione avviata. Fra un paio di minuti il sito è aggiornato.',
    'pubblica.tuttoOnline': 'Tutto quello che hai salvato è già sul sito.',
    'pubblica.maiPubblicato': 'Il sito non è ancora stato pubblicato da qui.',
    'pubblica.ultima': 'Ultima pubblicazione',
    'pubblica.senzaHook':
      'La pubblicazione automatica non è ancora configurata: le modifiche vanno online al prossimo aggiornamento del sito.',
    'pubblica.impostaHook': 'Configura',

    'comune.caricamento': 'Caricamento',
    'comune.errore': 'Qualcosa non ha funzionato.',
    'comune.riprova': 'Riprova',
    'comune.annulla': 'Annulla',
    'comune.chiudi': 'Chiudi',
    'comune.conferma': 'Conferma',
    'comune.salva': 'Salva',
    'comune.salvato': 'Salvato',
    'comune.elimina': 'Elimina',
    'comune.modifica': 'Modifica',
    'comune.nuovo': 'Nuovo',
    'comune.cerca': 'Cerca',
    'comune.nessunRisultato': 'Nessun risultato.',
    'comune.caricaImmagine': 'Carica una foto',
    'comune.trascinaImmagine': 'oppure trascinala qui',
    'comune.caricamentoFoto': 'Carico la foto',
    'comune.immagineTroppoGrande': 'La foto è troppo grande (massimo 20 MB).',
    'comune.formatoNonValido': 'Il file non è una foto.',
    'comune.copiato': 'Copiato',
    'comune.adesso': 'adesso',
    'comune.minutiFa': 'min fa',
    'comune.oreFa': 'ore fa',
    'comune.ieri': 'ieri',
    'comune.giorniFa': 'giorni fa',
    'comune.indietro': 'Indietro',
    'comune.sul': 'su',
    'comune.attenzione': 'Attenzione',
  },

  ro: {
    'menu.aria': 'Secțiunile panoului',
    'menu.pannello': 'Panou',
    'menu.richieste': 'Cereri',
    'menu.blog': 'Blog',
    'menu.lavori': 'Lucrări',
    'menu.recensioni': 'Recenzii',
    'menu.statistiche': 'Statistici',
    'menu.link': 'Linkuri',
    'menu.impostazioni': 'Setări',
    'menu.vediSito': 'Vezi site-ul',
    'menu.esci': 'Ieșire',
    'menu.contenuti': 'Conținut',
    'menu.clienti': 'Clienți',
    'menu.analisi': 'Analiză',
    'menu.altro': 'Altele',
    'menu.nuoveRichieste': 'cereri necitite',

    'locale.titolo': 'Mod de probă: datele rămân în acest browser',
    'locale.testo':
      'Panoul nu e legat la bază: ce scrii rămâne pe calculatorul ăsta și nu ajunge pe site. Ca să-l legi îți trebuie variabilele PUBLIC_SUPABASE_URL și PUBLIC_SUPABASE_ANON_KEY.',

    'accesso.titolo': 'Zonă rezervată',
    'accesso.sottotitolo': 'Intră ca să administrezi site-ul.',
    'accesso.frase': 'Site-ul tău, mereu la zi: cereri, lucrări, recenzii și articole într-un singur loc.',
    'accesso.email': 'Email',
    'accesso.password': 'Parolă',
    'accesso.entra': 'Intră',
    'accesso.attesa': 'O clipă',
    'accesso.errore': 'Email sau parolă greșite.',
    'accesso.nonAutorizzato': 'Contul ăsta nu are acces la panou.',
    'accesso.locale': 'În modul de probă se intră fără parolă.',
    'accesso.entraProva': 'Intră în modul de probă',
    'accesso.mostraPassword': 'Arată parola',
    'accesso.nascondiPassword': 'Ascunde parola',
    'accesso.dimenticata': 'Ai uitat parola?',
    'accesso.recuperoTitolo': 'Recuperează parola',
    'accesso.recuperoTesto': 'Scrie emailul: primești un link ca să alegi o parolă nouă.',
    'accesso.recuperoInvia': 'Trimite-mi linkul',
    'accesso.recuperoInviato': 'Gata. Verifică emailul, inclusiv spamul, și deschide linkul.',
    'accesso.torna': 'Înapoi la intrare',
    'accesso.nuovaPasswordTitolo': 'Alege o parolă nouă',
    'accesso.nuovaPasswordTesto': 'Cel puțin 8 caractere. Scrie-o de două ori, pentru siguranță.',
    'accesso.nuovaPassword': 'Parolă nouă',
    'accesso.confermaPassword': 'Repetă parola',
    'accesso.salvaPassword': 'Salvează parola',
    'accesso.passwordCambiata': 'Parola a fost schimbată. De acum intri cu cea nouă.',
    'accesso.passwordCorta': 'Parola trebuie să aibă cel puțin 8 caractere.',
    'accesso.passwordDiverse': 'Cele două parole nu coincid.',

    'pannello.titolo': 'Panou',
    'pannello.buongiorno': 'Bună dimineața',
    'pannello.buonPomeriggio': 'Bună ziua',
    'pannello.buonasera': 'Bună seara',
    'pannello.benvenuto': 'Așa stă site-ul chiar acum.',
    'pannello.nuovoArticolo': 'Articol nou',
    'pannello.oggi': 'Azi',
    'pannello.setteGiorni': 'Ultimele 7 zile',
    'pannello.trentaGiorni': 'Ultimele 30 de zile',
    'pannello.visualizzazioni': 'afișări de pagină',
    'pannello.visiteUniche': 'vizite unice',
    'pannello.vediStatistiche': 'Vezi toate statisticile',
    'pannello.richiesteNuove': 'Cereri necitite',
    'pannello.richiesteNuoveNota': 'oameni care așteaptă un răspuns',
    'pannello.nessunaNuova': 'Totul e răspuns, bravo.',
    'pannello.vediRichieste': 'Vezi cererile',
    'pannello.ultimeRichieste': 'Ultimele cereri',
    'pannello.nessunaRichiesta': 'Nicio cerere încă. Apar aici imediat ce cineva completează un formular pe site.',
    'pannello.ultimiArticoli': 'Ultimele articole',
    'pannello.nessunArticolo': 'Niciun articol încă. Apasă „Articol nou” și scrie primul.',
    'pannello.scorciatoie': 'Scurtături',
    'pannello.scriviArticoli': 'Scrie un articol',
    'pannello.aggiungiLavoro': 'Adaugă o lucrare',
    'pannello.aggiungiRecensione': 'Adaugă o recenzie',
    'pannello.creaLink': 'Creează un link de urmărire',
    'pannello.vediTraffico': 'Vezi cifrele de trafic',
    'pannello.cambiaDati': 'Schimbă telefonul și datele',
    'pannello.ilSito': 'Site-ul',
    'pannello.articoliPubblicati': 'articole publicate',
    'pannello.recensioniAttive': 'recenzii pe site',
    'pannello.cantieri': 'lucrări în galerie',
    'pannello.esempiAttivi': 'Site-ul arată încă exemplele: adaugă lucrările și recenziile tale reale.',
    'pannello.curva': 'Evoluția lunii',

    'richieste.titolo': 'Cereri',
    'richieste.sottotitolo': 'Cine a completat un formular pe site. Sună, scrie pe WhatsApp, bifează când ai răspuns.',
    'richieste.tutte': 'Toate',
    'richieste.nuove': 'Necitite',
    'richieste.contattate': 'Contactate',
    'richieste.chiuse': 'Închise',
    'richieste.vuoto': 'Nicio cerere încă.',
    'richieste.vuotoNuove': 'Nicio cerere necitită. Excelent.',
    'richieste.vuotoFiltro': 'Nimic în lista asta.',
    'richieste.tipoRichiamo': 'Sunat înapoi',
    'richieste.tipoPreventivo': 'Ofertă',
    'richieste.chiama': 'Sună',
    'richieste.whatsapp': 'WhatsApp',
    'richieste.email': 'Email',
    'richieste.statoNuova': 'Necitită',
    'richieste.statoContattata': 'Contactată',
    'richieste.statoChiusa': 'Închisă',
    'richieste.segnaContattata': 'Marchează contactată',
    'richieste.segnaChiusa': 'Închide',
    'richieste.riapri': 'Redeschide',
    'richieste.nota': 'Notițe',
    'richieste.notaSegnaposto': 'De ex. sună marți, vrea vizita sâmbătă',
    'richieste.salvaNota': 'Salvează notițele',
    'richieste.cancella': 'Șterge',
    'richieste.confermaCancella': 'Ștergi cererea? Nu se mai poate reveni.',
    'richieste.dettagli': 'Detalii',
    'richieste.comune': 'Localitate',
    'richieste.servizio': 'Serviciu',
    'richieste.messaggio': 'Mesaj',
    'richieste.stima': 'Estimare afișată',
    'richieste.pagina': 'Pagină',
    'richieste.arrivataDa': 'Venită din linkul',
    'richieste.ricevuta': 'Primită',
    'richieste.senzaNome': 'Fără nume',
    'richieste.cerca': 'Caută după nume, telefon sau localitate',
    'richieste.whatsappTesto': 'Buongiorno, sono MDA Impresa Edile. Ho ricevuto la sua richiesta dal sito.',

    'blog.titolo': 'Blog',
    'blog.sottotitolo': 'Articolele publicate pe site. Fiecare articol ajută site-ul pe Google.',
    'blog.nuovo': 'Articol nou',
    'blog.vuoto': 'Niciun articol încă.',
    'blog.vuotoTesto': 'Un articol pe lună despre acoperișuri, infiltrații și întreținere aduce vizite din Google ani de zile.',
    'blog.bozza': 'Ciornă',
    'blog.pubblicato': 'Publicat',
    'blog.modifica': 'Modifică',
    'blog.cancella': 'Șterge',
    'blog.confermaCancella': 'Ștergi articolul? Nu se mai poate reveni.',
    'blog.tuttiArticoli': 'Toate articolele',
    'blog.nuovoTitolo': 'Articol nou',
    'blog.modificaTitolo': 'Modifică articolul',
    'blog.campoTitolo': 'Titlu',
    'blog.segnapostoTitolo': 'De ex. Când merită refăcut acoperișul în loc să-l repari',
    'blog.campoSlug': 'Adresă (slug)',
    'blog.aiutoSlug': 'Articolul va avea adresa',
    'blog.slugOccupato': 'Alt articol folosește deja adresa asta.',
    'blog.campoEstratto': 'Introducere',
    'blog.aiutoEstratto': 'Una sau două fraze afișate în lista blogului și pe Google.',
    'blog.campoCopertina': 'Imagine de copertă',
    'blog.scegliImmagine': 'Încarcă o poză',
    'blog.togliCopertina': 'Scoate coperta',
    'blog.campoContenuto': 'Conținut',
    'blog.segnapostoContenuto':
      'Scrie articolul aici.\n\nRândurile goale creează paragrafe noi. Folosește butoanele de sus pentru aldin, cursiv, subtitluri, liste, linkuri și poze.',
    'blog.anteprima': 'Așa va arăta pe site',
    'blog.anteprimaVuota': 'Previzualizarea apare pe măsură ce scrii.',
    'blog.salva': 'Salvează',
    'blog.salvato': 'Salvat',
    'blog.grassetto': 'Aldin',
    'blog.corsivo': 'Cursiv',
    'blog.sottotitolo2': 'Subtitlu',
    'blog.elenco': 'Listă',
    'blog.link': 'Link',
    'blog.immagine': 'Poză',
    'blog.chiediLink': 'Adresa linkului',
    'blog.serveTitolo': 'Îți trebuie măcar un titlu ca să salvezi.',
    'blog.vediSulSito': 'Vezi pe site',
    'blog.parole': 'cuvinte',
    'blog.minutiLettura': 'min de citit',
    'blog.pubblicaNota': 'Oprit: articolul rămâne ciornă, o vezi doar tu. Pornit: merge pe site.',
    'blog.stato': 'Stare',

    'lavori.titolo': 'Lucrări',
    'lavori.sottotitolo':
      'Lucrările cu poza înainte și după, cum apar pe site. Până adaugi una, site-ul arată exemplele.',
    'lavori.nuovo': 'Lucrare nouă',
    'lavori.vuotoTitolo': 'Nicio lucrare de-a ta încă',
    'lavori.vuotoTesto': 'Site-ul arată cinci exemple. Adaugă prima lucrare reală cu două poze, înainte și după, și exemplele dispar.',
    'lavori.esempiNota': 'Pe site sunt încă exemplele: imediat ce o lucrare de-a ta e vizibilă, le ia locul.',
    'lavori.nuovoTitolo': 'Lucrare nouă',
    'lavori.modificaTitolo': 'Modifică lucrarea',
    'lavori.campoTitolo': 'Titlu',
    'lavori.segnapostoTitolo': 'De ex. Refacere acoperiș la Portogruaro',
    'lavori.campoLocalita': 'Localitate',
    'lavori.segnapostoLocalita': 'De ex. Portogruaro (VE)',
    'lavori.campoTesto': 'Descriere',
    'lavori.segnapostoTesto': 'De ex. Refacere completă a acoperișului cu țiglă portugheză și izolație din vată minerală.',
    'lavori.campoDurata': 'Durata lucrării',
    'lavori.segnapostoDurata': 'De ex. 8 zile lucrătoare',
    'lavori.campoMateriali': 'Materiale folosite',
    'lavori.segnapostoMateriali': 'De ex. Vată minerală, cupru, țiglă',
    'lavori.prima': 'Înainte',
    'lavori.dopo': 'După',
    'lavori.caricaFoto': 'Încarcă poza',
    'lavori.cambiaFoto': 'Schimbă',
    'lavori.visibile': 'Vizibilă pe site',
    'lavori.nascosto': 'Ascunsă',
    'lavori.salva': 'Salvează',
    'lavori.cancella': 'Șterge',
    'lavori.confermaCancella': 'Ștergi lucrarea? Pozele dispar de pe site.',
    'lavori.serveTitolo': 'Îți trebuie un titlu.',
    'lavori.serveFoto': 'Îți trebuie ambele poze, înainte și după.',
    'lavori.su': 'Mută sus',
    'lavori.giu': 'Mută jos',
    'lavori.modifica': 'Modifică',

    'recensioni.titolo': 'Recenzii',
    'recensioni.sottotitolo':
      'Cuvintele clienților tăi, copiate de pe Google sau din mesajele lor. Până adaugi una, site-ul arată exemplele.',
    'recensioni.nuova': 'Recenzie nouă',
    'recensioni.vuotoTitolo': 'Nicio recenzie de-a ta încă',
    'recensioni.vuotoTesto': 'Copiază aici recenziile reale ale clienților: nume, localitate și cuvintele lor. Exemplele dispar singure.',
    'recensioni.esempiNota': 'Pe site sunt încă exemplele: imediat ce o recenzie de-a ta e vizibilă, le ia locul.',
    'recensioni.googleNota': 'Doar recenzii reale: cele inventate sunt publicitate înșelătoare și Google le penalizează.',
    'recensioni.nuovaTitolo': 'Recenzie nouă',
    'recensioni.modificaTitolo': 'Modifică recenzia',
    'recensioni.campoNome': 'Numele clientului',
    'recensioni.segnapostoNome': 'De ex. Giovanni S.',
    'recensioni.campoLocalita': 'Localitate',
    'recensioni.segnapostoLocalita': 'De ex. San Donà di Piave (VE)',
    'recensioni.campoTesto': 'Recenzia',
    'recensioni.segnapostoTesto': 'Cuvintele clientului, așa cum le-a scris.',
    'recensioni.campoVoto': 'Stele',
    'recensioni.stelle': 'stele din 5',
    'recensioni.campoFoto': 'Poză (opțional)',
    'recensioni.caricaFoto': 'Încarcă o poză',
    'recensioni.togliFoto': 'Scoate poza',
    'recensioni.fotoNota': 'Fără poză, site-ul arată inițialele numelui.',
    'recensioni.visibile': 'Vizibilă pe site',
    'recensioni.nascosta': 'Ascunsă',
    'recensioni.salva': 'Salvează',
    'recensioni.cancella': 'Șterge',
    'recensioni.confermaCancella': 'Ștergi recenzia?',
    'recensioni.serveTesto': 'Îți trebuie numele și textul recenziei.',
    'recensioni.su': 'Mută sus',
    'recensioni.giu': 'Mută jos',
    'recensioni.modifica': 'Modifică',

    'statistiche.titolo': 'Statistici',
    'statistiche.sottotitolo': 'Vizitele site-ului, fără cookie-uri și fără a stoca nimic despre vizitatori.',
    'statistiche.settegiorni': '7 zile',
    'statistiche.trentagiorni': '30 de zile',
    'statistiche.novantagiorni': '90 de zile',
    'statistiche.dodicimesi': '12 luni',
    'statistiche.visualizzazioni': 'Afișări de pagină',
    'statistiche.uniche': 'Vizite unice',
    'statistiche.piuVista': 'Cea mai văzută',
    'statistiche.daMobile': 'De pe mobil',
    'statistiche.periodo': 'în perioada aleasă',
    'statistiche.sessioni': 'sesiuni, câte una pe vizitator și filă',
    'statistiche.percentuale': 'procent din sesiuni',
    'statistiche.visitePerGiorno': 'Vizite pe zi',
    'statistiche.vediTabella': 'Vezi tabelul',
    'statistiche.vediGrafico': 'Vezi graficul',
    'statistiche.paginePiuViste': 'Cele mai văzute pagini',
    'statistiche.provenienza': 'De unde au venit vizitele',
    'statistiche.dispositivi': 'Dispozitive',
    'statistiche.trafficoLink': 'Trafic din linkurile tale',
    'statistiche.diretto': 'Direct sau adresă tastată',
    'statistiche.computer': 'Calculator',
    'statistiche.telefono': 'Mobil',
    'statistiche.nessunDato': 'Încă nicio dată pentru perioada asta.',
    'statistiche.giorno': 'Ziua',
    'statistiche.nota': 'Vizitele tale din panou nu sunt numărate.',

    'link.titolo': 'Linkuri',
    'link.sottotitolo':
      'Adrese de folosit într-un anunț, pe un pliant sau pe Facebook: cine intră de aici e numărat separat, ca să știi ce funcționează.',
    'link.nuovo': 'Link nou',
    'link.etichetta': 'Nume (pentru tine)',
    'link.segnapostoEtichetta': 'De ex. Pliant septembrie',
    'link.codice': 'Cod',
    'link.destinazione': 'Unde duce',
    'link.crea': 'Creează',
    'link.copia': 'Copiază',
    'link.copiato': 'Copiat',
    'link.cancella': 'Șterge',
    'link.confermaCancella': 'Ștergi linkul? Cine îl deschide ajunge oricum pe prima pagină.',
    'link.vuoto': 'Niciun link încă.',
    'link.vuotoTesto': 'Creează un link diferit pentru fiecare pliant sau anunț și vezi care aduce mai multe vizite.',
    'link.visite': 'Vizite',
    'link.visualizzazioni': 'Afișări',
    'link.serveEtichetta': 'Îți trebuie un nume și un cod.',
    'link.codiceUsato': 'Codul ăsta există deja.',
    'link.home': 'Prima pagină',
    'link.servizi': 'Servicii',
    'link.guide': 'Ghiduri',
    'link.zone': 'Zone deservite',
    'link.preventivo': 'Ofertă (prima pagină)',
    'link.blog': 'Blog',

    'impostazioni.titolo': 'Setări',
    'impostazioni.sottotitolo': 'Datele firmei care apar pe site. Ce lași gol rămâne cum e acum.',
    'impostazioni.contatti': 'Contact',
    'impostazioni.contattiNota': 'Apar sus, în subsol și în butoanele de apel.',
    'impostazioni.telefono': 'Telefon',
    'impostazioni.aiutoTelefono': 'Cum vrei să apară scris, de ex. +39 389 999 7498',
    'impostazioni.whatsapp': 'Număr WhatsApp',
    'impostazioni.aiutoWhatsapp': 'Doar cifre cu prefix, de ex. 393899997498. Gol: folosește telefonul.',
    'impostazioni.email': 'Email',
    'impostazioni.orari': 'Program',
    'impostazioni.aiutoOrari': 'De ex. Lun - Sab, 08:00 - 18:00',
    'impostazioni.oreRisposta': 'Răspuns în (ore)',
    'impostazioni.garanziaAnni': 'Garanție (ani)',
    'impostazioni.sede': 'Sediu',
    'impostazioni.via': 'Strada și numărul',
    'impostazioni.cap': 'Cod poștal',
    'impostazioni.citta': 'Localitate',
    'impostazioni.provincia': 'Sigla provinciei',
    'impostazioni.aiutoProvincia': 'De ex. VE',
    'impostazioni.provinciaNome': 'Numele provinciei',
    'impostazioni.aiutoProvinciaNome': 'De ex. Venezia',
    'impostazioni.legale': 'Date legale',
    'impostazioni.legaleNota':
      'Obligatorii prin lege pe un site de firmă în Italia. Cât lipsesc, site-ul nu le publică și nu inventează nimic.',
    'impostazioni.ragioneSociale': 'Denumirea firmei',
    'impostazioni.aiutoRagioneSociale': 'De ex. MDA Impresa Edile S.r.l., ca în registru',
    'impostazioni.partitaIva': 'Partita IVA',
    'impostazioni.aiutoPartitaIva': 'Unsprezece cifre, de ex. IT01234567890',
    'impostazioni.rea': 'Număr REA',
    'impostazioni.aiutoRea': 'De ex. VE-123456. Gol dacă firma nu e înregistrată.',
    'impostazioni.social': 'Social',
    'impostazioni.instagram': 'Pagina Instagram',
    'impostazioni.facebook': 'Pagina Facebook',
    'impostazioni.salva': 'Salvează setările',
    'impostazioni.salvato': 'Setări salvate',
    'impostazioni.pubblicazione': 'Publicare',
    'impostazioni.pubblicazioneNota':
      'Site-ul se regenerează singur când apeși Publică. Cererile și statisticile nu au nevoie de asta.',
    'impostazioni.hook': 'Adresa de publicare (Deploy Hook din Vercel)',
    'impostazioni.aiutoHook': 'O creează cine a construit site-ul, din Vercel: Settings, Git, Deploy Hooks. Se lipește aici o singură dată.',
    'impostazioni.salvaHook': 'Salvează adresa',
    'impostazioni.account': 'Accesul tău',
    'impostazioni.accountEmail': 'Intri cu',
    'impostazioni.nuovaPassword': 'Parolă nouă',
    'impostazioni.confermaPassword': 'Repetă parola nouă',
    'impostazioni.cambiaPassword': 'Schimbă parola',
    'impostazioni.passwordCambiata': 'Parola a fost schimbată',
    'impostazioni.lingua': 'Limba panoului',

    'pubblica.daPubblicare': 'Sunt modificări care nu sunt încă pe site.',
    'pubblica.pubblica': 'Publică pe site',
    'pubblica.inCorso': 'Publicare în curs, durează cam două minute.',
    'pubblica.fatto': 'Publicarea a pornit. În câteva minute site-ul e la zi.',
    'pubblica.tuttoOnline': 'Tot ce ai salvat e deja pe site.',
    'pubblica.maiPubblicato': 'Site-ul nu a fost încă publicat de aici.',
    'pubblica.ultima': 'Ultima publicare',
    'pubblica.senzaHook':
      'Publicarea automată nu e încă configurată: modificările ajung online la următoarea actualizare a site-ului.',
    'pubblica.impostaHook': 'Configurează',

    'comune.caricamento': 'Se încarcă',
    'comune.errore': 'Ceva nu a mers.',
    'comune.riprova': 'Încearcă din nou',
    'comune.annulla': 'Anulează',
    'comune.chiudi': 'Închide',
    'comune.conferma': 'Confirmă',
    'comune.salva': 'Salvează',
    'comune.salvato': 'Salvat',
    'comune.elimina': 'Șterge',
    'comune.modifica': 'Modifică',
    'comune.nuovo': 'Nou',
    'comune.cerca': 'Caută',
    'comune.nessunRisultato': 'Niciun rezultat.',
    'comune.caricaImmagine': 'Încarcă o poză',
    'comune.trascinaImmagine': 'sau trage-o aici',
    'comune.caricamentoFoto': 'Încarc poza',
    'comune.immagineTroppoGrande': 'Poza e prea mare (maxim 20 MB).',
    'comune.formatoNonValido': 'Fișierul nu e o poză.',
    'comune.copiato': 'Copiat',
    'comune.adesso': 'acum',
    'comune.minutiFa': 'min în urmă',
    'comune.oreFa': 'ore în urmă',
    'comune.ieri': 'ieri',
    'comune.giorniFa': 'zile în urmă',
    'comune.indietro': 'Înapoi',
    'comune.sul': 'pe',
    'comune.attenzione': 'Atenție',
  },
} as const

export type Chiave = keyof (typeof TESTI)['it']

let corrente: Lingua = 'it'
try {
  const salvata = localStorage.getItem(CHIAVE)
  if (salvata === 'it' || salvata === 'ro') corrente = salvata
} catch {
  /* modalità privata: resta l'italiano */
}

/** Traduce una chiave. Se manca nella lingua scelta si ripiega sull'italiano. */
export function t(c: Chiave): string {
  return (TESTI[corrente] as Record<string, string>)[c] ?? TESTI.it[c] ?? c
}

export function lingua(): Lingua {
  return corrente
}

/** Codice locale per date e numeri, allineato alla lingua scelta. */
export function locale(): string {
  return corrente === 'ro' ? 'ro-RO' : 'it-IT'
}

/**
 * Cambia lingua e ricarica: tutti i testi sono già stampati nel DOM, e
 * ridisegnare a mano ogni pagina costerebbe più codice di quanto valga per
 * un'azione che si fa una volta sola.
 */
export function cambiaLingua(l: Lingua): void {
  corrente = l
  try {
    localStorage.setItem(CHIAVE, l)
  } catch {
    /* la scelta vale per questa sessione */
  }
  location.reload()
}

/* --- DATE ----------------------------------------------------------------- */

/** "1 settembre 2026". Stringa vuota se la data non si legge. */
export function dataLeggibile(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString(locale(), { day: 'numeric', month: 'long', year: 'numeric' })
}

/** "01 set 2026", per le tabelle. */
export function dataBreve(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString(locale(), { day: '2-digit', month: 'short', year: 'numeric' })
}

/** "1 set, 14:30". */
export function dataOra(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleString(locale(), { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })
}

/**
 * "adesso", "12 min fa", "3 ore fa", "ieri", "5 giorni fa", poi la data.
 * Per le richieste: quanto tempo aspetta una persona conta più della data.
 */
export function tempoFa(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  const secondi = Math.max(0, (Date.now() - d.getTime()) / 1000)
  if (secondi < 90) return t('comune.adesso')
  const minuti = Math.round(secondi / 60)
  if (minuti < 60) return `${minuti} ${t('comune.minutiFa')}`
  const ore = Math.round(minuti / 60)
  if (ore < 24) return `${ore} ${t('comune.oreFa')}`
  const giorni = Math.round(ore / 24)
  if (giorni === 1) return t('comune.ieri')
  if (giorni < 7) return `${giorni} ${t('comune.giorniFa')}`
  return dataBreve(iso)
}

/** I numeri escono con il separatore delle migliaia della lingua scelta. */
export function numero(n: number): string {
  return n.toLocaleString(locale())
}
